### PR TITLE
feat: fix chat negotiations + cleanup dashboard ui

### PR DESCRIPTION
**Pull request by anyuan-chen**

### CODE REVIEW

**Review by petemango — CHANGES_REQUESTED** [review]
please remove `.env` and add `.DS_Store` to gitignore

**Review by petemango — APPROVED** [review]
lgtm 🚀

**Comment by jamesxsu** [comment]
lgtm

**Comment by anyuan-chen** [comment]
> lgtm 🚀

you don't lgtm :(

**Comment by jamesxsu** [comment]
thats ok ur mom thinks so

**Pull request merged**
